################################################################################
##																			  ##
##                     			MASTER RUN								      ##
##																			  ##
################################################################################
## WARNING: when executed from a working directory, it is required to specify  #
## the path of the .mod, .dat, and .run files from the working directory.      #
################################################################################

# Load model
model "/Users/achuat/Documents/Projects/Governance_EnergyScope/EnergyScopePy_dev/case_studies/Mobility/es_model.mod";

# Load data
data "/Users/achuat/Documents/Projects/Governance_EnergyScope/EnergyScopePy_dev/case_studies/Mobility/ESTD_data.dat";
#data "/Users/achuat/Documents/Projects/Governance_EnergyScope/EnergyScopePy_dev/case_studies_initial/ESTD_data.dat";

data "/Users/achuat/Documents/Projects/Governance_EnergyScope/EnergyScopePy_dev/case_studies/Mobility/ESTD_12TD.dat";

# Run options
option show_stats "3";
option log_file "/Users/achuat/Documents/Projects/Governance_EnergyScope/EnergyScopePy_dev/case_studies/Mobility/output/log.txt";
option presolve "10";
option presolve_eps "1e-7";
option presolve_fixeps "1e-7";
option show_boundtol "0";
option _log_input_only "False";
option solver "cplex";
option gurobi_options "predual=-1 method=2 crossover=0 prepasses=3 barconvtol=1e-6 presolve=-1";

#option omit_zero_rows 1;                            
#option omit_zero_cols 1;
#display end_uses_input["MOBILITY_PASSENGER_SD"];
#expand layers_in_out;

# Solve
solve;
option times 0; # show time
option gentimes 0; # show time

#display solve_result;
#display solve_result_num;
#display _solve_elapsed_time;
#display F;
#expand operating_strategy_mob_passenger_SD;

# Saving sets and parameters to output file
param PathName symbolic := "/Users/achuat/Documents/Projects/Governance_EnergyScope/EnergyScopePy_dev/case_studies/Mobility/output";

if solve_result = "limit" then { # To avoid post treatment error
    print "TIME OUT";
    exit 1;
}
else {
    if solve_result = "infeasible" then {
        print "INFEASIBLE";
        exit 1;
    }
    else {
        if solve_result = "failure" then {
            print "FAILURE";
            exit 1;
        }
        else {
			include "/Users/achuat/Documents/Projects/Governance_EnergyScope/EnergyScopePy_dev/energyscope/energy_model/run/print_year_summary.run";
			include "/Users/achuat/Documents/Projects/Governance_EnergyScope/EnergyScopePy_dev/energyscope/energy_model/run/print_hourly_data.run";
			include "/Users/achuat/Documents/Projects/Governance_EnergyScope/EnergyScopePy_dev/energyscope/energy_model/run/print_sankey.run";
			exit 0;
		}
	}
}